FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD testweb2-0.0.1-SNAPSHOT.war app.jar
RUN sh -c 'touch /app.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]

